//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPGMaps
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelMaster
    {
        public int HotelID { get; set; }
        public string HotelArea { get; set; }
        public string HotelName { get; set; }
        public string LocLat { get; set; }
        public string LocLong { get; set; }
        public string ReadMoreUrl { get; set; }
    }
}
