//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPGMaps
{
    using System;
    using System.Collections.Generic;
    
    public partial class subject
    {
        public int subject_id { get; set; }
        public string subject_name { get; set; }
        public Nullable<int> category_fid { get; set; }
        public string category_name { get; set; }
    }
}
