//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPGMaps
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempHeart
    {
        public int Id { get; set; }
        public string Student_Name { get; set; }
        public string Temp { get; set; }
        public string Bmp { get; set; }
        public string DateTime { get; set; }
    }
}
