//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPGMaps
{
    using System;
    using System.Collections.Generic;
    
    public partial class usrdata
    {
        public int usrID { get; set; }
        public string user_id_number { get; set; }
        public string user_rank { get; set; }
        public string user_department { get; set; }
        public string usercategory { get; set; }
        public string user_fname { get; set; }
        public string user_lname { get; set; }
        public string user_username { get; set; }
        public string user_password { get; set; }
        public string user_gender { get; set; }
        public string user_dob { get; set; }
        public string user_force_number { get; set; }
        public string user_mobile { get; set; }
        public string user_email { get; set; }
        public string user_address { get; set; }
        public byte[] user_picture { get; set; }
    }
}
