//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASPGMaps
{
    using System;
    using System.Collections.Generic;
    
    public partial class vent
    {
        public int EventID { get; set; }
        public string Subject { get; set; }
        public string event_description { get; set; }
        public System.DateTime start_date { get; set; }
    }
}
